# Generated by Django 5.0.3 on 2024-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNum',
            field=models.CharField(default='NULL', max_length=11),
        ),
    ]
