# Generated by Django 5.0.3 on 2024-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_note_profile_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parentName',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
