# Generated by Django 5.0.3 on 2024-04-09 18:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_phonenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phoneNum',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
